### ISSUE TITLE
[Page] Data overview

### ISSUE THREAD

**Issue by alexaib2002** [alexaib2002/dam2-final-project#5]
## Description

Users should be able to access an overview where DB contents should be displayed. They may create, remove or modify registers.

Ideally, this should be tailored to each client requirements, but a basic table view should be enough as a placeholder.

## TODO

- [x] Register creation modal
- [x] Register deletion button (each register should have their own)
- [x] Register modify button (each register should have their own)
- [x] Overview
- [ ] (?) Some way to instruct the app how data should be displayed (extension scripts?)

## Depends

List of issues in which this feature depends (may be empty):

- #3 (Full functionality integration)

**Comment by alexaib2002** [comment]
Register deletion will be implemented with DataGrid selection events, and modification will be done by suscribing to DataGrid events

**Comment by alexaib2002** [comment]
Everything originally proposed has already been implemented. As for how will the app display the data, it will be discussed in a future issue.
